name: dart_bot
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dependencies:
  teledart: ^0.2.1
  http: ^0.13.4
  rxdart: ^0.27.3

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
